services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.production
    ports:
      - "${APP_PORT:-80}:80"
    networks:
      - net
    depends_on:
      db:
        condition: service_healthy

  db:
    image: "mariadb:latest"
    healthcheck:
      test:
        - CMD
        - healthcheck.sh
        - "--connect"
        - "--innodb_initialized"
      retries: 3
      timeout: 5s
    environment:
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_DATABASE: "${DB_DATABASE}"
      MARIADB_ROOT_HOST: "%"
      MARIADB_USER: "${DB_USERNAME}"
      MARIADB_ROOT_PASSWORD: "${DB_PASSWORD}"
      MARIADB_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - "data:/var/lib/mysql"
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  data:
    driver: local
