export enum NotificationType {
    MISSION_ACCOMPLISHED = "MISSION_ACCOMPLISHED",
    COMMENT_RECEIVED = "COMMENT_RECEIVED",
    REPLY_RECEIVED = "REPLY_RECEIVED",
    POST_VOTE_RECEIVED = "POST_VOTE_RECEIVED",
    COMMENT_VOTE_RECEIVED = "COMMENT_VOTE_RECEIVED",
    COMMENT_MARKED = "COMMENT_MARKED"
}
