export enum ReportReason {
    SPAM_OR_CHEATING = "SPAM_OR_CHEATING",
    INAPPROPRIATE = "INAPPROPRIATE",
    OFFENSIVE_LANGUAGE = "OFFENSIVE_LANGUAGE",
    HARASSMENT = "HARASSMENT",
    OTHER = "OTHER"
}
