<?php

namespace App\Enums;

enum MissionType: string
{
    // Account Related (Non Configurable)
    case EMAIL_VERIFICATION = 'EMAIL_VERIFICATION';
    case LINKING_WITH_PROVIDERS = 'LINKING_WITH_PROVIDERS';
    case PROFILE_SETUP = 'PROFILE_SETUP';

    // Stats
    case LOGIN_STREAK = 'LOGIN_STREAK';
    case LEVEL = 'LEVEL';
    case XP_TOTAL = 'XP_TOTAL';
    case XP_DAILY = 'XP_DAILY';
    case XP_WEEKLY = 'XP_WEEKLY';
    case XP_MONTHLY = 'XP_MONTHLY';
    case XP_YEARLY = 'XP_YEARLY';
    case TIMESPENT = "TIMESPENT";

    // Posts and Comments
    case TOTAL_OWNED_POSTS = 'TOTAL_OWNED_POSTS';
    case TOTAL_OWNED_ARTICLES = 'TOTAL_OWNED_ARTICLES';
    case TOTAL_OWNED_QUESTIONS = 'TOTAL_OWNED_QUESTIONS';
    case TOTAL_OWNED_SUBJECTS = 'TOTAL_OWNED_SUBJECTS';
    case TOTAL_MARKED_COMMENTS = 'TOTAL_MARKED_COMMENTS';
    case TOTAL_MADE_COMMENTS = 'TOTAL_MADE_COMMENTS';

    // Posts Votes
    case MADE_POSTS_VOTE_UPS = 'MADE_POSTS_VOTE_UPS';
    case MADE_POSTS_VOTE_DOWNS = 'MADE_POSTS_VOTE_DOWNS';
    case RECEIVED_POSTS_VOTE_UPS = 'RECEIVED_POSTS_VOTE_UPS';

    // Comments Votes
    case MADE_COMMENTS_VOTE_UPS = 'MADE_COMMENTS_VOTE_UPS';
    case MADE_COMMENTS_VOTE_DOWNS = 'MADE_COMMENTS_VOTE_DOWNS';
    case RECEIVED_COMMENTS_VOTE_UPS = 'RECEIVED_COMMENTS_VOTE_UPS';

}
