<?php

namespace App\Enums;

enum MissionType: string
{
    // Login streak tracking
    case LOGIN_STREAK = 'LOGIN_STREAK';

    // XP
    case XP_TOTAL = 'XP_TOTAL';

    // Posts and Comments
    case TOTAL_OWNED_POSTS = 'TOTAL_OWNED_POSTS';
    case TOTAL_OWNED_ARTICLES = 'TOTAL_OWNED_ARTICLES';
    case TOTAL_OWNED_QUESTIONS = 'TOTAL_OWNED_QUESTIONS';
    case TOTAL_OWNED_SUBJECTS = 'TOTAL_OWNED_SUBJECTS';
    case TOTAL_MARKED_COMMENTS = 'TOTAL_MARKED_COMMENTS';
    case TOTAL_MADE_COMMENTS = 'TOTAL_MADE_COMMENTS';

    // Posts Votes
    case MADE_POSTS_VOTE_UPS = 'MADE_POSTS_VOTE_UPS';
    case MADE_POSTS_VOTE_DOWNS = 'MADE_POSTS_VOTE_DOWNS';
    case RECEIVED_POSTS_VOTE_UPS = 'RECEIVED_POSTS_VOTE_UPS';

    // Comments Votes
    case MADE_COMMENTS_VOTE_UPS = 'MADE_COMMENTS_VOTE_UPS';
    case MADE_COMMENTS_VOTE_DOWNS = 'MADE_COMMENTS_VOTE_DOWNS';
    case RECEIVED_COMMENTS_VOTE_UPS = 'RECEIVED_COMMENTS_VOTE_UPS';

    // Custom missions
    case CUSTOM = 'CUSTOM';
}
