name: Deployment Workflow

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6.16.0
        with:
          tags: |
            ${{ secrets.DOCKER_REGISTRY }}/stackmente:latest
            ${{ secrets.DOCKER_REGISTRY }}/stackmente:${{ github.sha }}
          push: true
          file: Dockerfile
          context: .

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: ${{ github.repository }}
        uses: cssnr/stack-deploy-action@v1.3.1
        with:
          file: docker-compose.production.yml
          user: root
          host: ${{ secrets.DEPLOY_SSH_HOST }}
          ssh_key: ${{ secrets.DEPLOY_SSH_KEY }}
